import worker from "./src/index.js";
const calls = [];
globalThis.fetch = async (url, init) => { calls.push({ url, method: init.method, headers: init.headers, body: init.body, signal: init.signal }); return new Response(JSON.stringify({ data: [] }), { status: 200, headers: { "content-type": "application/json" } }); };
const env = { CURSEFORGE_API_KEY: "TESTKEY", LIMITER: { async limit() { return { success: true }; } } };
const run = async (method, path, body, headers) => (await worker.fetch(new Request("https://p.example" + path, { method, body, headers }), env)).status;
const check = async (label, got, want) => console.log(got === want ? "ok  " : "FAIL", label, got);
await check("Suche", await run("GET", "/v1/mods/search?gameId=432&classId=6&searchFilter=jei&pageSize=20&index=9900"), 200);
await check("Suche fremdes Spiel", await run("GET", "/v1/mods/search?gameId=1&classId=6"), 400);
await check("Suche fremde Klasse", await run("GET", "/v1/mods/search?gameId=432&classId=17"), 400);
await check("Suche große Seite", await run("GET", "/v1/mods/search?gameId=432&classId=6&pageSize=500"), 400);
await check("Suche Seite NaN", await run("GET", "/v1/mods/search?gameId=432&classId=6&pageSize=abc"), 400);
await check("Suche Seite 0", await run("GET", "/v1/mods/search?gameId=432&classId=6&pageSize=0"), 400);
await check("Suche Index negativ", await run("GET", "/v1/mods/search?gameId=432&classId=6&index=-1"), 400);
await check("Suche hinter 10 000", await run("GET", "/v1/mods/search?gameId=432&classId=6&index=9990&pageSize=20"), 400);
await check("Suche fremder Parameter", await run("GET", "/v1/mods/search?gameId=432&classId=6&slug=jei"), 400);
await check("Mod", await run("GET", "/v1/mods/238222"), 200);
await check("Beschreibung", await run("GET", "/v1/mods/238222/description"), 200);
await check("Dateien", await run("GET", "/v1/mods/238222/files?gameVersion=1.20.1&pageSize=50"), 200);
await check("Datei", await run("GET", "/v1/mods/238222/files/4593548"), 200);
await check("POST files", await run("POST", "/v1/mods/files", JSON.stringify({ fileIds: [1, 2, 3] })), 200);
await check("POST mods", await run("POST", "/v1/mods", JSON.stringify({ modIds: [1] })), 200);
await check("POST falsches Feld", await run("POST", "/v1/mods/files", JSON.stringify({ modIds: [1] })), 400);
await check("POST Extra-Feld", await run("POST", "/v1/mods", JSON.stringify({ modIds: [1], x: 1 })), 400);
await check("POST zu viele", await run("POST", "/v1/mods", JSON.stringify({ modIds: Array.from({ length: 201 }, (_, i) => i + 1) })), 400);
await check("POST kaputt", await run("POST", "/v1/mods", "{"), 400);
await check("Browser (Origin)", await run("GET", "/v1/mods/238222", undefined, { origin: "https://evil.example" }), 403);
await check("Fingerprints", await run("POST", "/v1/fingerprints", "{}"), 404);
await check("Games", await run("GET", "/v1/games"), 404);
await check("Download-URL", await run("GET", "/v1/mods/1/files/2/download-url"), 404);
await check("DELETE", await run("DELETE", "/v1/mods/1"), 404);
await check("Wurzel", await run("GET", "/"), 404);
const n = calls.length; await run("GET", "/v1/mods/238222"); await check("Kein Zwischenspeicher (neuer Abruf)", calls.length, n + 1);
await check("Key, User-Agent und Timeout bei jedem Abruf", calls.every((c) => c.headers["x-api-key"] === "TESTKEY" && c.headers["user-agent"].includes("github.com") && c.signal), true);
const limited = { ...env, LIMITER: { async limit() { return { success: false }; } } };
const throttled = await worker.fetch(new Request("https://p.example/v1/mods/1"), limited);
await check("Limit", throttled.status, 429);
await check("Limit nennt Wartezeit", throttled.headers.get("retry-after"), "60");
await check("ohne Secret", (await worker.fetch(new Request("https://p.example/v1/mods/1"), {})).status, 500);
const callsBefore = calls.length;
await check("ohne Begrenzung (fail-closed)", (await worker.fetch(new Request("https://p.example/v1/mods/1"), { CURSEFORGE_API_KEY: "TESTKEY" })).status, 503);
await check("ohne Begrenzung nichts an CurseForge", calls.length, callsBefore);
const keys = [];
const spy = { ...env, LIMITER: { async limit({ key }) { keys.push(key); return { success: true }; } } };
await worker.fetch(new Request("https://p.example/v1/mods/1", { headers: { "cf-connecting-ip": "203.0.113.7" } }), spy);
await worker.fetch(new Request("https://p.example/v1/mods/1"), spy);
await check("Begrenzung je IP, ohne IP ein gemeinsamer Eimer", keys.join(","), "203.0.113.7,unbekannt");
globalThis.fetch = async () => new Response("{}", { status: 429, headers: { "content-type": "application/json", "retry-after": "17" } });
await check("Wartezeit von CurseForge kommt durch", (await worker.fetch(new Request("https://p.example/v1/mods/1"), env)).headers.get("retry-after"), "17");
globalThis.fetch = async () => { throw new DOMException("timeout", "TimeoutError"); };
await check("CurseForge hängt", await run("GET", "/v1/mods/1"), 504);
