import worker from "./src/index.js";
const calls = [];
globalThis.caches = { default: { store: new Map(), async match(r) { return this.store.get(r.url)?.clone(); }, async put(r, res) { this.store.set(r.url, res); } } };
globalThis.fetch = async (url, init) => { calls.push({ url, method: init.method, key: init.headers["x-api-key"], body: init.body }); return new Response(JSON.stringify({ data: [] }), { status: 200, headers: { "content-type": "application/json" } }); };
const env = { CURSEFORGE_API_KEY: "TESTKEY", LIMITER: { async limit() { return { success: true }; } } };
const ctx = { waitUntil: (p) => p };
const run = async (method, path, body) => (await worker.fetch(new Request("https://p.example" + path, { method, body }), env, ctx)).status;
const check = async (label, got, want) => console.log(got === want ? "ok  " : "FAIL", label, got);
await check("Suche", await run("GET", "/v1/mods/search?gameId=432&classId=6&searchFilter=jei&pageSize=20"), 200);
await check("Suche fremdes Spiel", await run("GET", "/v1/mods/search?gameId=1&classId=6"), 400);
await check("Suche fremde Klasse", await run("GET", "/v1/mods/search?gameId=432&classId=17"), 400);
await check("Suche große Seite", await run("GET", "/v1/mods/search?gameId=432&classId=6&pageSize=500"), 400);
await check("Mod", await run("GET", "/v1/mods/238222"), 200);
await check("Beschreibung", await run("GET", "/v1/mods/238222/description"), 200);
await check("Dateien", await run("GET", "/v1/mods/238222/files?gameVersion=1.20.1"), 200);
await check("Datei", await run("GET", "/v1/mods/238222/files/4593548"), 200);
await check("POST files", await run("POST", "/v1/mods/files", JSON.stringify({ fileIds: [1, 2, 3] })), 200);
await check("POST mods", await run("POST", "/v1/mods", JSON.stringify({ modIds: [1] })), 200);
await check("POST falsches Feld", await run("POST", "/v1/mods/files", JSON.stringify({ modIds: [1] })), 400);
await check("POST Extra-Feld", await run("POST", "/v1/mods", JSON.stringify({ modIds: [1], x: 1 })), 400);
await check("POST zu viele", await run("POST", "/v1/mods", JSON.stringify({ modIds: Array.from({ length: 201 }, (_, i) => i + 1) })), 400);
await check("POST kaputt", await run("POST", "/v1/mods", "{"), 400);
await check("Fingerprints", await run("POST", "/v1/fingerprints", "{}"), 404);
await check("Games", await run("GET", "/v1/games"), 404);
await check("Download-URL", await run("GET", "/v1/mods/1/files/2/download-url"), 404);
await check("DELETE", await run("DELETE", "/v1/mods/1"), 404);
await check("Wurzel", await run("GET", "/"), 404);
const n = calls.length; await run("GET", "/v1/mods/238222"); await check("Cache (kein neuer Abruf)", calls.length, n);
console.log("Key wird angehängt:", calls.every((c) => c.key === "TESTKEY"), "| Abrufe:", calls.length);
const limited = { ...env, LIMITER: { async limit() { return { success: false }; } } };
await check("Limit", (await worker.fetch(new Request("https://p.example/v1/mods/1"), limited, ctx)).status, 429);
await check("ohne Secret", (await worker.fetch(new Request("https://p.example/v1/mods/1"), {}, ctx)).status, 500);
